### ISSUE TITLE
Remove pre-requesites installation

### ISSUE THREAD

**Issue by mario4tier** [ChainMovers/suibase#101]
Update 6/20/24: Goal changed to eliminate the Sui pre-requesites.

**Goals**

(1) ~~Should detect the Sui prerequesites missing and automatically (or offer) to the user to install them.~~ Suibase CLI should automatically download, install and upgrade suibase-daemon binaries without user intervention.

(2) The installation of the VSCode extension should have the consequence of installing Suibase CLI ~~and the Sui pre-requesites automatically~~. Ideally, that means to be fully up and running only by installing the extension!

**Related code**
VSCode extension for now just do diagnostic... not automated installation:

![image](https://github.com/ChainMovers/suibase/assets/4542410/1654b784-ead3-4828-97c5-480d77063c58)
Excerpt from https://github.com/ChainMovers/suibase/blob/main/typescript/vscode-extension/src/BackendSync.ts

The CLI look for pre-requesites when attempting to build something:

![image](https://github.com/ChainMovers/suibase/assets/4542410/38f2fda9-a697-4a84-a416-814166ea3b75)
Excerpt from https://github.com/ChainMovers/suibase/blob/main/scripts/common/__globals.sh

**Comment by kkomelin** [comment]
Hey @mario4tier ,

As I mentioned during our chat discussion, some of my users (kkomelin/sui-dapp-starter) complained about the complexity of the Sui prerequisites installation.

My suggestion was to develop OS-specific shell scripts to install everything in one line like so:

```bash
# Windows
iwr https://get.pnpm.io/install.ps1 -useb | iex
# Linux
wget -qO- https://get.pnpm.io/install.sh | sh -
```
ref https://pnpm.io/installation

And I thought about suggesting adding them to the main Sui docs/repo because I think it's a higher level problem.

I like the checks which Suibase has. It may be enough. What is the best place to add the scrips from your point of view?

**Comment by kkomelin** [comment]
Currently Sui docs offer one-liners for Mac:
```
brew install sui
# or 
choco install sui
```

I don't know a person who would have `brew` or `choco` installed on Linux/Ubuntu. Native package managers here are `apt` and `span`. Maybe it's easier to suggest Sui adding a Span package for Linux/Ubuntu and that would eliminate the need of manual dependency install.

**Comment by mario4tier** [comment]
I see. 

Seems that they are properly now favoring pre-compiled binaries, therefore eliminating the need for most pre-requesites.

IMHO, it is now becoming more urgent to *also* eliminate having Suibase depends on these Sui prerequesites (which are currently needed for building the Rust suibase-daemon).

===

For suibase, the binary installation should remain to be done with directly downloading "assets". Not brew/choco etc... the reasons are:

- updates through brew "lag" the assets release, sometimes by many days. I don't know if better/worst with choco, but this is a part of the process we do not control.

- suibase supports forcing an older assets version (needed when Mysten Labs break something in their devnet branch. This did happen twice already). Not sure how to easily manage that with brew/choco.

**Comment by kkomelin** [comment]
Thank you @mario4tier ,

Agree, let's leave streamlining Sui cli prerequisites installation to the Sui guys. Can suggest this improvement to them later with lower priority.

As for Suibase, it looks like if we could implement building suibase-daemon in the cloud for all OSs automatically, we would not need to ask users to install Sui prerequisites at all, which would be ideal from my point of view because it would allow to simplify  Suibase and VSCode Plugin checks significantly. Shall we consider this option?

**Comment by mario4tier** [comment]
> As for Suibase, it looks like if we could implement building `suibase-daemon` in the cloud for all OSs automatically, we would not need to ask users to install Sui prerequisites at all, which would be ideal from my point of view because it would allow to simplify Suibase and VSCode Plugin checks significantly. Shall we consider this option?

Yes. I fully agree.

I plan to complete this by end of August (will be done with github actions, which already build the suibase-daemon for automated tests).

The Suibase assets will match the way Mysten Labs release their assets, that way we can re-use most of the already done bash script.

**Comment by kkomelin** [comment]
@mario4tier That's a good plan! Good luck with that! I have Lunux/Ubuntu if you need some alfa/beta testers. Can also try to setup Windows through VirtualBox.

**Comment by mario4tier** [comment]
Done. Suibase does not require Sui prerequisites anymore (notably, rust installation is not needed).

See https://suibase.io/how-to/install.html

===

Advanced users can still force compilation with ```precompiled_bin: false``` in suibase.yaml. In this case, Suibase will inform the user to install rustc (if not already done). See [force to build locally](https://suibase.io/how-to/configure-suibase-yaml.html#force-to-build-locally) in docs.

**Comment by kkomelin** [comment]
@mario4tier Man, it's insane! Thank you! It's a great UX improment. How did you achieve that?

**Comment by mario4tier** [comment]
At high level, Suibase identify the user platform/arch and download the assets from github (when an higher version is detected).

For sui (and walrus in the future), it downloads directly from Mysten Labs.

In the case of suibase-daemon (or any other open-source Rust tool that we choose to integrate later), a Cargo.toml *version* change in the Suibase repos trig an action (with an automated push) in another [sui-binaries repos](
https://github.com/ChainMovers/sui-binaries)

After the builds, a last github job verify the assets are valid for all platform/arch before tagging it as "released".

![image](https://github.com/user-attachments/assets/d97f213d-212d-48aa-8aa9-105e3bc7e10f)

**Comment by mario4tier** [comment]
The next step in better UX is that suibase-daemon will periodically check for updates and have some kind of "Release X available" displayed when doing, say, "devnet status".

**Comment by kkomelin** [comment]
Thanks for explaining @mario4tier ! That's a solid piece of work. Great
