### ISSUE TITLE
Add Walrus integration docs to Suibase website

### ISSUE THREAD

**Issue by mario4tier** [ChainMovers/suibase#104]
Proposing the following changes:

(1) Add a new page named "Integration" under the "Suibase Docs" section.
(2) Add a "Walrus" section ( https://github.com/MystenLabs/walrus-sites/issues/94 )

**Comment by mario4tier** [comment]
@kkomelin an integration page has been added. Do you want to fill the Walrus section? (if yes, then just proceed at your convenience with the "edit" button on the page).

**Comment by kkomelin** [comment]
Sure. Thank you @mario4tier. I will do
