### ISSUE TITLE
Mainnet start compile error.

### ISSUE THREAD

**Issue by ccbond** [ChainMovers/suibase#114]
![image](https://github.com/user-attachments/assets/f229f9f8-6af0-41ad-90cf-048364978c8e)

**Comment by ccbond** [comment]
just run mainnet start

**Comment by mario4tier** [comment]
Suibase does not require compilation of suibase-daemon anymore (this is new from a commit done today).

Do "~/suibase/update" to try the latest.

(Note: I could not reproduce this probem)
