### ISSUE TITLE
Multi Concurrent Running Localnet

### ISSUE THREAD

**Issue by FrankC01** [ChainMovers/suibase#12]
Provide ability to have multiple-instances of localnet running

**Comment by mario4tier** [comment]
Summary
=======
I recommend to use multiple VM, one per localnet.

Details
=======
Now that we have more experience... I end up running 3x localnet simultaneously using VM (MacOS VM +  Windows 11/WSL2 VM + Linux Ubuntu host).

This is working well, particularly when the VM uses the precompiled Sui binaries (Suibase fully installed in <2 minutes and no need for a lot of assigned vCPU).

I think this is a good workaround versus having Suibase deal with all sort of conflicts (particularly, managements of "ports" for the local process).

I found the user experience also good (just click on the VM window... there is nothing needed on the CLI for the user to "switch" from one "localnet" to another).
