### ISSUE TITLE
Discord wick bot image does not show up.

### ISSUE THREAD

**Issue by georgescharlesbrain** [ChainMovers/suibase#61]
![image](https://github.com/ChainMovers/suibase/assets/72499006/f20d8882-c72b-461f-a8e4-1cc3a5604d29)
 Clicking to see the attachment doesnt do anything.
Tried removing the discord and joining again. No win there.

**Comment by georgescharlesbrain** [comment]
incognito mode or android app also did not work. Issue was solved by manually getting access.

**Comment by mario4tier** [comment]
Thanks for reporting this.

Another user was able to verify around the same time, so it might be intermittent or specific to a user setting.

I did stumble on the following, don't know if related (something about "enabling embed link option"):
  https://www.reddit.com/r/rocketpool/comments/q1x1ak/wickbot_verification/ 

Will re-open if I see other users stuck in non-verified state.
