### ISSUE TITLE
How to deploy to mainnet using a hardware wallet?

### ISSUE THREAD

**Issue by georgescharlesbrain** [ChainMovers/suibase#63]
What are the best practices to deploy to mainnet?

How to use a hardware wallet and multi-sig?

**Comment by mario4tier** [comment]
Not sure if this is a common use case for Suibase (at least not on short term).

Suibase focus right now is to facilitate development and testing. I was even seeing the "mainnet" workdir for relatively light fund use (e.g. testing with other mainnet deployed modules). For such purpose, a relatively "risky" sui.keystore seems good enough.

I will leave this open to accumulate feedback.

**Comment by georgescharlesbrain** [comment]
It was more of a general question that came to mind when thinking about the different key stores for different networks. Maybe it's something the sui foundation should/could address.
