### ISSUE TITLE
Why does it take 1min (localnet start) for NFTs to show up in the suiexplorer?

### ISSUE THREAD

**Issue by georgescharlesbrain** [ChainMovers/suibase#64]
Hello,

I had the impression that the local network was reset at every stop. The objects I created during start\_stop\_1 didn't appear in the suiexplorer after a new local network start. Now I figured out they do show up but only after 1min.
Any idea why they show up only after 1 min?

,KR GCB

**Comment by mario4tier** [comment]
1 minute is surprising. 

I test with a module publication and the whole edit/publish/debug cycle (where debug means calling into it and receiving event to confirm it works) takes less than 30 seconds (with 1.4.0). 

Wondering what would be different with the NFT/suiexplorer scenario.

==

Did check that the latest (1.5.0) sui process still come up quickly on start, but have not test more than that today. Will revisit this later (will prioritize your other open issues for now).

**Comment by georgescharlesbrain** [comment]
This is a non-issue imo. Just learnings that might be useful for future starters of suibase.
