### ISSUE TITLE
storage management

### ISSUE THREAD

**Issue by georgescharlesbrain** [ChainMovers/suibase#67]
I've noticed that 1 network workdir takes up around 30GB and that it has something to do with the target/debug folders of cargo.

A note in the docs next to the update statement about the size and using cargo clean or another automated process for managing the size could be useful I think.

**Comment by georgescharlesbrain** [comment]
[discord](https://discord.com/channels/1038616996062953554/1081836316330831892/1124276699459244083) for more info
Issue can be closed for me.

**Comment by mario4tier** [comment]
Thanks for the discussion. This has evolve into #68, including an action item for the docs.
