### ISSUE TITLE
request timeout on "dsui client gas"

### ISSUE THREAD

**Issue by georgescharlesbrain** [ChainMovers/suibase#82]
Having some issues here with suibase.

steps taken:
~/suibase/update
Current version 0.1.5-1b9b167

devnet update
devnet_proxy │ http://0.0.0.0:44341               │ *      │
devnet       │ https://fullnode.devnet.sui.io:443

"dsui client gas" gives
Request timeout

**Comment by georgescharlesbrain** [comment]
"sui client gas" did work

**Comment by mario4tier** [comment]
Is it intermittent or all the time?

Can you please show me the output of "devnet links"? (to see the health of the RPC servers from your setup).

**Comment by mario4tier** [comment]
If you are block by this, you can try disabling the proxy with adding ```proxy_enabled: false``` in ```~/suibase/workdirs/devnet/suibase.yaml``` followed by "devnet stop" and start to make sure the config is well applied.

...but I would prefer to figure out the problem when you have time.

**Comment by georgescharlesbrain** [comment]
"devnet links" does not return anything, it just hangs

proxy\_enabled: false --> dsui client gas works

proxy\_enabled: true + devnet  stop & start   
\--> dsui client gas gives request timeout

\--> devnet links still no return

**Comment by georgescharlesbrain** [comment]
1,2 : Ubuntu

![](https://github.com/ChainMovers/suibase/assets/72499006/7eb96853-658d-495a-b082-de51142cf751)

3: devnet stop, devnet start after setting proxy\_enabled: true  
devnet status --> no return

4\. devnet status: nothing is being returned in output, log:  
\[_2023-10-21T08:04:02Z_ INFO jsonrpsee\_server::server\] Accepting new connection 1/100

ctrl+c  
\[_2023-10-21T08:06:55Z_ WARN jsonrpsee\_server::server\] HTTP serve connection failed hyper::Error(IncompleteMessage)

devnet status: nothing is being returned in output, log:  
\[_2023-10-21T08:07:00Z_ INFO jsonrpsee\_server::server\] Accepting new connection 1/100

**Comment by georgescharlesbrain** [comment]
See resolution in #83
