### ISSUE TITLE
localnet start gives "sui process not responding"

### ISSUE THREAD

**Issue by georgescharlesbrain** [ChainMovers/suibase#83]
```
(base) ➜  move git:(main) localnet start 
Starting localnet process
..............................(may take some time on slower system).....................
Sui process not responding. Try again? (may be the host is too slow?).
```

Will check if I get a localnet running using the suidocs.  
Its not that I changed my laptop.

**Comment by FrankC01** [comment]
For the short fix, find the `sui-deamon` PID and kill it. Then do `localnet start` again...

**Comment by georgescharlesbrain** [comment]
I didn't find the attach file option, so I pasted it below.

\[_2023-10-15T11:38:02Z_ INFO suibase\_daemon::clock\_trigger\] started

\[_2023-10-15T11:38:02Z_ INFO suibase\_daemon::network\_monitor\] started

\[_2023-10-15T11:38:02Z_ INFO suibase\_daemon::api::api\_server\] APIServer started

\[_2023-10-15T11:38:02Z_ INFO suibase\_daemon::api::api\_server\] JSONRPCServer server started

\[_2023-10-15T11:38:02Z_ INFO suibase\_daemon::admin\_controller\] started

\[_2023-10-15T11:38:02Z_ INFO suibase\_daemon::workdirs\_watcher\] started

\[_2023-10-15T11:38:02Z_ INFO suibase\_daemon::workdirs\_watcher\] watching /home/koen/suibase/workdirs/testnet

\[_2023-10-15T11:38:02Z_ INFO suibase\_daemon::workdirs\_watcher\] watching /home/koen/suibase/workdirs/testnet/.state

\[_2023-10-15T11:38:02Z_ INFO suibase\_daemon::workdirs\_watcher\] Sending notif /home/koen/suibase/workdirs/testnet

\[_2023-10-15T11:38:02Z_ INFO suibase\_daemon::workdirs\_watcher\] watching /home/koen/suibase/workdirs/devnet

\[_2023-10-15T11:38:02Z_ INFO suibase\_daemon::workdirs\_watcher\] watching /home/koen/suibase/workdirs/devnet/.state

\[_2023-10-15T11:38:02Z_ INFO suibase\_daemon::workdirs\_watcher\] Sending notif /home/koen/suibase/workdirs/devnet

\[_2023-10-15T11:38:02Z_ INFO suibase\_daemon::workdirs\_watcher\] watching /home/koen/suibase/workdirs/localnet

\[_2023-10-15T11:38:02Z_ INFO suibase\_daemon::workdirs\_watcher\] watching /home/koen/suibase/workdirs/localnet/.state

\[_2023-10-15T11:38:02Z_ INFO suibase\_daemon::workdirs\_watcher\] Sending notif /home/koen/suibase/workdirs/localnet

\[_2023-10-15T11:38:02Z_ INFO suibase\_daemon::workdirs\_watcher\] watcher PollWatcher { watches: Mutex { data: {"/home/koen/suibase/workdirs/testnet/.state": WatchData { root: "/home/koen/suibase/workdirs/testnet/.state", is\_recursive: false, all\_path\_data: {"/home/koen/suibase/workdirs/testnet/.state/user\_request": PathData { mtime: 1695575349, hash: None, last\_check: Instant { tv\_sec: 1527, tv\_nsec: 953284218 } }, "/home/koen/suibase/workdirs/testnet/.state/links": PathData { mtime: 1693753476, hash: None, last\_check: Instant { tv\_sec: 1527, tv\_nsec: 953284218 } }, "/home/koen/suibase/workdirs/testnet/.state/dns": PathData { mtime: 1688033353, hash: None, last\_check: Instant { tv\_sec: 1527, tv\_nsec: 953284218 } }, "/home/koen/suibase/workdirs/testnet/.state/precompiled": PathData { mtime: 1695575349, hash: None, last\_check: Instant { tv\_sec: 1527, tv\_nsec: 953284218 } }, "/home/koen/suibase/workdirs/testnet/.state": PathData { mtime: 1695575349, hash: None, last\_check: Instant { tv\_sec: 1527, tv\_nsec: 953284218 } }, "/home/koen/suibase/workdirs/testnet/.state/name": PathData { mtime: 1688031911, hash: None, last\_check: Instant { tv\_sec: 1527, tv\_nsec: 953284218 } }} }, "/home/koen/suibase/workdirs/devnet/.state": WatchData { root: "/home/koen/suibase/workdirs/devnet/.state", is\_recursive: false, all\_path\_data: {"/home/koen/suibase/workdirs/devnet/.state": PathData { mtime: 1693231114, hash: None, last\_check: Instant { tv\_sec: 1527, tv\_nsec: 953527786 } }, "/home/koen/suibase/workdirs/devnet/.state/dns": PathData { mtime: 1688060014, hash: None, last\_check: Instant { tv\_sec: 1527, tv\_nsec: 953527786 } }, "/home/koen/suibase/workdirs/devnet/.state/user\_request": PathData { mtime: 1693232634, hash: None, last\_check: Instant { tv\_sec: 1527, tv\_nsec: 953527786 } }, "/home/koen/suibase/workdirs/devnet/.state/name": PathData { mtime: 1688056047, hash: None, last\_check: Instant { tv\_sec: 1527, tv\_nsec: 953527786 } }, "/home/koen/suibase/workdirs/devnet/.state/links": PathData { mtime: 1693231114, hash: None, last\_check: Instant { tv\_sec: 1527, tv\_nsec: 953527786 } }} }, "/home/koen/suibase/workdirs/devnet": WatchData { root: "/home/koen/suibase/workdirs/devnet", is\_recursive: false, all\_path\_data: {"/home/koen/suibase/workdirs/devnet/workdir-exec": PathData { mtime: 1688056047, hash: None, last\_check: Instant { tv\_sec: 1527, tv\_nsec: 953373981 } }, "/home/koen/suibase/workdirs/devnet/.state": PathData { mtime: 1693231114, hash: None, last\_check: Instant { tv\_sec: 1527, tv\_nsec: 953373981 } }, "/home/koen/suibase/workdirs/devnet/sui-repo": PathData { mtime: 1693231234, hash: None, last\_check: Instant { tv\_sec: 1527, tv\_nsec: 953373981 } }, "/home/koen/suibase/workdirs/devnet/config": PathData { mtime: 1693232634, hash: None, last\_check: Instant { tv\_sec: 1527, tv\_nsec: 953373981 } }, "/home/koen/suibase/workdirs/devnet/suibase.yaml": PathData { mtime: 1693435540, hash: None, last\_check: Instant { tv\_sec: 1527, tv\_nsec: 953373981 } }, "/home/koen/suibase/workdirs/devnet/logs": PathData { mtime: 1688056047, hash: None, last\_check: Instant { tv\_sec: 1527, tv\_nsec: 953373981 } }, "/home/koen/suibase/workdirs/devnet/config-default": PathData { mtime: 1693232634, hash: None, last\_check: Instant { tv\_sec: 1527, tv\_nsec: 953373981 } }, "/home/koen/suibase/workdirs/devnet": PathData { mtime: 1688062341, hash: None, last\_check: Instant { tv\_sec: 1527, tv\_nsec: 953373981 } }, "/home/koen/suibase/workdirs/devnet/sui-repo-default": PathData { mtime: 1693231234, hash: None, last\_check: Instant { tv\_sec: 1527, tv\_nsec: 953373981 } }, "/home/koen/suibase/workdirs/devnet/published-data": PathData { mtime: 1688062341, hash: None, last\_check: Instant { tv\_sec: 1527, tv\_nsec: 953373981 } }, "/home/koen/suibase/workdirs/devnet/sui-exec": PathData { mtime: 1688056047, hash: None, last\_check: Instant { tv\_sec: 1527, tv\_nsec: 953373981 } }} }, "/home/koen/suibase/workdirs": WatchData { root: "/home/koen/suibase/workdirs", is\_recursive: false, all\_path\_data: {"/home/koen/suibase/workdirs/devnet": PathData { mtime: 1688062341, hash: None, last\_check: Instant { tv\_sec: 1527, tv\_nsec: 952711580 } }, "/home/koen/suibase/workdirs/testnet": PathData { mtime: 1695575138, hash: None, last\_check: Instant { tv\_sec: 1527, tv\_nsec: 952711580 } }, "/home/koen/suibase/workdirs/localnet": PathData { mtime: 1697369882, hash: None, last\_check: Instant { tv\_sec: 1527, tv\_nsec: 952711580 } }, "/home/koen/suibase/workdirs/common": PathData { mtime: 1693212425, hash: None, last\_check: Instant { tv\_sec: 1527, tv\_nsec: 952711580 } }, "/home/koen/suibase/workdirs/cargobin": PathData { mtime: 1688026872, hash: None, last\_check: Instant { tv\_sec: 1527, tv\_nsec: 952711580 } }, "/home/koen/suibase/workdirs": PathData { mtime: 1693211858, hash: None, last\_check: Instant { tv\_sec: 1527, tv\_nsec: 952711580 } }, "/home/koen/suibase/workdirs/active": PathData { mtime: 1697369882, hash: None, last\_check: Instant { tv\_sec: 1527, tv\_nsec: 952711580 } }} }, "/home/koen/suibase/workdirs/localnet": WatchData { root: "/home/koen/suibase/workdirs/localnet", is\_recursive: false, all\_path\_data: {"/home/koen/suibase/workdirs/localnet": PathData { mtime: 1697369882, hash: None, last\_check: Instant { tv\_sec: 1527, tv\_nsec: 953591056 } }, "/home/koen/suibase/workdirs/localnet/workdir-exec": PathData { mtime: 1688027750, hash: None, last\_check: Instant { tv\_sec: 1527, tv\_nsec: 953591056 } }, "/home/koen/suibase/workdirs/localnet/sui-repo": PathData { mtime: 1697369880, hash: None, last\_check: Instant { tv\_sec: 1527, tv\_nsec: 953591056 } }, "/home/koen/suibase/workdirs/localnet/logs": PathData { mtime: 1688027750, hash: None, last\_check: Instant { tv\_sec: 1527, tv\_nsec: 953591056 } }, "/home/koen/suibase/workdirs/localnet/config-default": PathData { mtime: 1697369881, hash: None, last\_check: Instant { tv\_sec: 1527, tv\_nsec: 953591056 } }, "/home/koen/suibase/workdirs/localnet/faucet": PathData { mtime: 1697369882, hash: None, last\_check: Instant { tv\_sec: 1527, tv\_nsec: 953591056 } }, "/home/koen/suibase/workdirs/localnet/sui-repo-default": PathData { mtime: 1697369880, hash: None, last\_check: Instant { tv\_sec: 1527, tv\_nsec: 953591056 } }, "/home/koen/suibase/workdirs/localnet/.state": PathData { mtime: 1695285948, hash: None, last\_check: Instant { tv\_sec: 1527, tv\_nsec: 953591056 } }, "/home/koen/suibase/workdirs/localnet/config": PathData { mtime: 1697369881, hash: None, last\_check: Instant { tv\_sec: 1527, tv\_nsec: 953591056 } }, "/home/koen/suibase/workdirs/localnet/.cache": PathData { mtime: 1694709357, hash: None, last\_check: Instant { tv\_sec: 1527, tv\_nsec: 953591056 } }, "/home/koen/suibase/workdirs/localnet/suibase.yaml": PathData { mtime: 1695285629, hash: None, last\_check: Instant { tv\_sec: 1527, tv\_nsec: 953591056 } }, "/home/koen/suibase/workdirs/localnet/genesis-data": PathData { mtime: 1697369881, hash: None, last\_check: Instant { tv\_sec: 1527, tv\_nsec: 953591056 } }, "/home/koen/suibase/workdirs/localnet/sui-exec": PathData { mtime: 1688027750, hash: None, last\_check: Instant { tv\_sec: 1527, tv\_nsec: 953591056 } }} }, "/home/koen/suibase/workdirs/localnet/.state": WatchData { root: "/home/koen/suibase/workdirs/localnet/.state", is\_recursive: false, all\_path\_data: {"/home/koen/suibase/workdirs/localnet/.state/user\_request": PathData { mtime: 1697369882, hash: None, last\_check: Instant { tv\_sec: 1527, tv\_nsec: 953740739 } }, "/home/koen/suibase/workdirs/localnet/.state/links": PathData { mtime: 1695285773, hash: None, last\_check: Instant { tv\_sec: 1527, tv\_nsec: 953740739 } }, "/home/koen/suibase/workdirs/localnet/.state": PathData { mtime: 1695285948, hash: None, last\_check: Instant { tv\_sec: 1527, tv\_nsec: 953740739 } }, "/home/koen/suibase/workdirs/localnet/.state/name": PathData { mtime: 1688027750, hash: None, last\_check: Instant { tv\_sec: 1527, tv\_nsec: 953740739 } }, "/home/koen/suibase/workdirs/localnet/.state/precompiled": PathData { mtime: 1697369881, hash: None, last\_check: Instant { tv\_sec: 1527, tv\_nsec: 953740739 } }} }, "/home/koen/suibase/workdirs/testnet": WatchData { root: "/home/koen/suibase/workdirs/testnet", is\_recursive: false, all\_path\_data: {"/home/koen/suibase/workdirs/testnet/.state": PathData { mtime: 1695575349, hash: None, last\_check: Instant { tv\_sec: 1527, tv\_nsec: 953125476 } }, "/home/koen/suibase/workdirs/testnet/sui-repo": PathData { mtime: 1695575348, hash: None, last\_check: Instant { tv\_sec: 1527, tv\_nsec: 953125476 } }, "/home/koen/suibase/workdirs/testnet/published-data": PathData { mtime: 1688046358, hash: None, last\_check: Instant { tv\_sec: 1527, tv\_nsec: 953125476 } }, "/home/koen/suibase/workdirs/testnet/sui-exec": PathData { mtime: 1688031911, hash: None, last\_check: Instant { tv\_sec: 1527, tv\_nsec: 953125476 } }, "/home/koen/suibase/workdirs/testnet/logs": PathData { mtime: 1688031911, hash: None, last\_check: Instant { tv\_sec: 1527, tv\_nsec: 953125476 } }, "/home/koen/suibase/workdirs/testnet/workdir-exec": PathData { mtime: 1688031911, hash: None, last\_check: Instant { tv\_sec: 1527, tv\_nsec: 953125476 } }, "/home/koen/suibase/workdirs/testnet/.cache": PathData { mtime: 1695575140, hash: None, last\_check: Instant { tv\_sec: 1527, tv\_nsec: 953125476 } }, "/home/koen/suibase/workdirs/testnet/config-default": PathData { mtime: 1693754216, hash: None, last\_check: Instant { tv\_sec: 1527, tv\_nsec: 953125476 } }, "/home/koen/suibase/workdirs/testnet/config": PathData { mtime: 1693754216, hash: None, last\_check: Instant { tv\_sec: 1527, tv\_nsec: 953125476 } }, "/home/koen/suibase/workdirs/testnet/sui-repo-default": PathData { mtime: 1695575348, hash: None, last\_check: Instant { tv\_sec: 1527, tv\_nsec: 953125476 } }, "/home/koen/suibase/workdirs/testnet/suibase.yaml": PathData { mtime: 1693753446, hash: None, last\_check: Instant { tv\_sec: 1527, tv\_nsec: 953125476 } }, "/home/koen/suibase/workdirs/testnet": PathData { mtime: 1695575138, hash: None, last\_check: Instant { tv\_sec: 1527, tv\_nsec: 953125476 } }} }}, poisoned: false, .. }, data\_builder: Mutex { data: DataBuilder { build\_hasher: None, now: Instant { tv\_sec: 1527, tv\_nsec: 953740739 } }, poisoned: false, .. }, want\_to\_stop: false, delay: 15s }

\[_2023-10-15T11:38:02Z_ INFO suibase\_daemon::admin\_controller\] cfg notif testnet

\[_2023-10-15T11:38:02Z_ INFO suibase\_daemon::admin\_controller\] cfg notif devnet

\[_2023-10-15T11:38:02Z_ INFO suibase\_daemon::admin\_controller\] cfg notif localnet

\[_2023-10-15T11:38:02Z_ INFO suibase\_daemon::request\_worker\] started

\[_2023-10-15T11:38:02Z_ INFO suibase\_daemon::proxy\_server\] listening on 0.0.0.0:44342

\[_2023-10-15T11:38:02Z_ INFO suibase\_daemon::proxy\_server\] listening on 0.0.0.0:44341

\[_2023-10-15T11:38:02Z_ INFO suibase\_daemon::proxy\_server\] listening on 0.0.0.0:44340

\[_2023-10-15T11:38:03Z_ INFO jsonrpsee\_server::server\] Accepting new connection 1/100

\[_2023-10-15T11:38:17Z_ INFO suibase\_daemon::workdirs\_watcher\] Sending notif /home/koen/suibase/workdirs/localnet/suibase.yaml

\[_2023-10-15T11:39:45Z_ INFO jsonrpsee\_server::server\] Accepting new connection 1/100

\[_2023-10-15T11:39:45Z_ INFO suibase\_daemon::admin\_controller\] cfg notif localnet

\[_2023-10-15T11:39:47Z_ INFO suibase\_daemon::workdirs\_watcher\] Sending notif /home/koen/suibase/workdirs/localnet/.state/user\_request

\[_2023-10-15T11:39:49Z_ INFO jsonrpsee\_server::server\] Accepting new connection 1/100

\[_2023-10-15T11:39:49Z_ INFO suibase\_daemon::admin\_controller\] cfg notif localnet

\[_2023-10-15T11:40:02Z_ INFO suibase\_daemon::workdirs\_watcher\] Sending notif /home/koen/suibase/workdirs/localnet/.state/user\_request

\[_2023-10-15T11:40:57Z_ INFO jsonrpsee\_server::server\] Accepting new connection 1/100

\[_2023-10-15T11:40:57Z_ INFO suibase\_daemon::admin\_controller\] cfg notif localnet

\[_2023-10-15T11:41:02Z_ INFO suibase\_daemon::workdirs\_watcher\] Sending notif /home/koen/suibase/workdirs/localnet/.state/user\_request

\[_2023-10-17T19:17:03Z_ INFO jsonrpsee\_server::server\] Accepting new connection 1/100

\[_2023-10-17T19:17:03Z_ INFO suibase\_daemon::admin\_controller\] cfg notif localnet

\[_2023-10-17T19:17:04Z_ INFO suibase\_daemon::workdirs\_watcher\] Sending notif /home/koen/suibase/workdirs/localnet/.state/user\_request

\[_2023-10-17T19:18:45Z_ INFO jsonrpsee\_server::server\] Accepting new connection 1/100

\[_2023-10-17T19:19:28Z_ WARN jsonrpsee\_server::server\] HTTP serve connection failed hyper::Error(IncompleteMessage)

\[_2023-10-17T19:19:33Z_ INFO jsonrpsee\_server::server\] Accepting new connection 1/100

\[_2023-10-17T19:19:34Z_ INFO suibase\_daemon::workdirs\_watcher\] Sending notif /home/koen/suibase/workdirs/localnet/.state/user\_request

\[_2023-10-17T19:21:17Z_ INFO jsonrpsee\_server::server\] Accepting new connection 1/100

\[_2023-10-17T19:21:19Z_ INFO suibase\_daemon::workdirs\_watcher\] Sending notif /home/koen/suibase/workdirs/localnet/.state/user\_request

\[_2023-10-17T19:28:49Z_ INFO suibase\_daemon::workdirs\_watcher\] Sending notif /home/koen/suibase/workdirs/devnet/.state/user\_request

\[_2023-10-17T19:47:34Z_ INFO suibase\_daemon::workdirs\_watcher\] Sending notif /home/koen/suibase/workdirs/devnet/.state/user\_request

\[_2023-10-17T20:28:54Z_ INFO jsonrpsee\_server::server\] Accepting new connection 1/100

\[_2023-10-18T07:19:44Z_ INFO jsonrpsee\_server::server\] Accepting new connection 1/100

\[_2023-10-18T07:21:32Z_ INFO jsonrpsee\_server::server\] Accepting new connection 2/100

\[_2023-10-18T07:21:37Z_ WARN jsonrpsee\_server::server\] HTTP serve connection failed hyper::Error(IncompleteMessage)

\[_2023-10-18T07:21:42Z_ INFO jsonrpsee\_server::server\] Accepting new connection 2/100

\[_2023-10-18T07:21:48Z_ WARN jsonrpsee\_server::server\] HTTP serve connection failed hyper::Error(IncompleteMessage)

\[_2023-10-18T07:21:55Z_ INFO jsonrpsee\_server::server\] Accepting new connection 2/100

\[_2023-10-18T07:22:08Z_ INFO suibase\_daemon::workdirs\_watcher\] Sending notif /home/koen/suibase/workdirs/localnet/.state/user\_request

\[_2023-10-18T07:22:11Z_ WARN jsonrpsee\_server::server\] HTTP serve connection failed hyper::Error(IncompleteMessage)

\[_2023-10-18T07:23:08Z_ INFO jsonrpsee\_server::server\] Accepting new connection 1/100

\[_2023-10-18T07:23:11Z_ WARN jsonrpsee\_server::server\] HTTP serve connection failed hyper::Error(IncompleteMessage)

\[_2023-10-18T07:23:22Z_ INFO jsonrpsee\_server::server\] Accepting new connection 1/100

\[_2023-10-18T07:23:46Z_ WARN jsonrpsee\_server::server\] HTTP serve connection failed hyper::Error(IncompleteMessage)

\[_2023-10-18T07:23:52Z_ INFO jsonrpsee\_server::server\] Accepting new connection 1/100

\[_2023-10-18T07:26:53Z_ INFO suibase\_daemon::workdirs\_watcher\] Sending notif /home/koen/suibase/workdirs/devnet/suibase.yaml

\[_2023-10-18T07:29:26Z_ WARN jsonrpsee\_server::server\] HTTP serve connection failed hyper::Error(IncompleteMessage)

\[_2023-10-18T07:54:53Z_ INFO suibase\_daemon::workdirs\_watcher\] Sending notif /home/koen/suibase/workdirs/devnet/suibase.yaml

\[_2023-10-18T07:55:57Z_ INFO jsonrpsee\_server::server\] Accepting new connection 1/100

\[_2023-10-18T07:56:05Z_ INFO jsonrpsee\_server::server\] Accepting new connection 1/100

\[_2023-10-18T07:56:08Z_ INFO suibase\_daemon::workdirs\_watcher\] Sending notif /home/koen/suibase/workdirs/devnet/.state/user\_request

\[_2023-10-18T07:56:47Z_ INFO jsonrpsee\_server::server\] Accepting new connection 1/100

\[_2023-10-18T07:56:53Z_ INFO suibase\_daemon::workdirs\_watcher\] Sending notif /home/koen/suibase/workdirs/devnet/.state/user\_request

\[_2023-10-18T07:56:53Z_ INFO suibase\_daemon::workdirs\_watcher\] Sending notif /home/koen/suibase/workdirs/devnet/suibase.yaml

\[_2023-10-18T07:56:53Z_ INFO jsonrpsee\_server::server\] Accepting new connection 1/100

\[_2023-10-18T07:58:53Z_ INFO suibase\_daemon::workdirs\_watcher\] Sending notif /home/koen/suibase/workdirs/devnet/suibase.yaml

\[_2023-10-18T07:59:49Z_ INFO jsonrpsee\_server::server\] Accepting new connection 1/100

\[_2023-10-18T08:01:59Z_ WARN jsonrpsee\_server::server\] HTTP serve connection failed hyper::Error(IncompleteMessage)

\[_2023-10-18T13:50:55Z_ INFO suibase\_daemon::workdirs\_watcher\] Sending notif /home/koen/suibase/workdirs/devnet/suibase.yaml

\[_2023-10-18T13:51:18Z_ INFO jsonrpsee\_server::server\] Accepting new connection 1/100

\[_2023-10-18T13:51:25Z_ INFO suibase\_daemon::workdirs\_watcher\] Sending notif /home/koen/suibase/workdirs/localnet/.state/user\_request

\[_2023-10-18T13:52:29Z_ INFO jsonrpsee\_server::server\] Accepting new connection 1/100

\[_2023-10-18T14:00:50Z_ WARN jsonrpsee\_server::server\] HTTP serve connection failed hyper::Error(IncompleteMessage)

\[_2023-10-18T14:46:46Z_ INFO jsonrpsee\_server::server\] Accepting new connection 1/100

\[_2023-10-18T14:46:55Z_ INFO suibase\_daemon::workdirs\_watcher\] Sending notif /home/koen/suibase/workdirs/localnet/.state/user\_request

\[_2023-10-19T09:45:08Z_ INFO jsonrpsee\_server::server\] Accepting new connection 1/100

\[_2023-10-19T09:45:17Z_ INFO suibase\_daemon::workdirs\_watcher\] Sending notif /home/koen/suibase/workdirs/localnet/.state/user\_request

\[_2023-10-21T08:02:37Z_ INFO jsonrpsee\_server::server\] Accepting new connection 1/100

\[_2023-10-21T08:03:21Z_ WARN jsonrpsee\_server::server\] HTTP serve connection failed hyper::Error(IncompleteMessage)

\[_2023-10-21T08:03:28Z_ INFO suibase\_daemon::workdirs\_watcher\] Sending notif /home/koen/suibase/workdirs/devnet/suibase.yaml

\[_2023-10-21T08:03:35Z_ INFO jsonrpsee\_server::server\] Accepting new connection 1/100

\[_2023-10-21T08:03:39Z_ INFO jsonrpsee\_server::server\] Accepting new connection 1/100

\[_2023-10-21T08:03:43Z_ INFO suibase\_daemon::workdirs\_watcher\] Sending notif /home/koen/suibase/workdirs/devnet/.state/user\_request

\[_2023-10-21T08:04:02Z_ INFO jsonrpsee\_server::server\] Accepting new connection 1/100

\[_2023-10-21T08:06:55Z_ WARN jsonrpsee\_server::server\] HTTP serve connection failed hyper::Error(IncompleteMessage)

\[_2023-10-21T08:07:00Z_ INFO jsonrpsee\_server::server\] Accepting new connection 1/100

\[_2023-10-21T08:12:13Z_ WARN jsonrpsee\_server::server\] HTTP serve connection failed hyper::Error(IncompleteMessage)

**Comment by georgescharlesbrain** [comment]
Just now: works and then doesn't work:

````
```
(base) ➜  suibase git:(main) localnet start 
Starting localnet faucet
.
faucet started (process pid 1577700)
Switching sui client env from [localnet] to [localnet_proxy]
[localnet_proxy] added to client.yaml
(base) ➜  suibase git:(main) localnet stop 
Switching sui client env from [localnet_proxy] to [localnet]
Stopping faucet (process pid 1577700)
Stopping localnet (process pid 1105175)
localnet now stopped
(base) ➜  suibase git:(main) localnet start
Starting localnet process
..............................(may take some time on slower system)........................
Sui process not responding. Try again? (may be the host is too slow?).
````

Is there a time that I have to wait between calls?  
Should "localnet status" give a response when localnet is stopped?

**Comment by mario4tier** [comment]
Thanks for the info here and in #82.

Trying hard to make it reliable... so any input is greatly appreciated.

Now that it is working, I am wondering if this is because the suibase-daemon is not running anymore on your setup. In other word, did you keep the proxy disabled?

One sure way to verify if suibase-daemon is running is "lsof":

``` sh
~$ lsof /tmp/.suibase/suibase-daemon.lock 
COMMAND      PID USER   FD   TYPE DEVICE SIZE/OFF     NODE NAME
flock     912946 ----    3rW  REG  253,0        0 11666819 /tmp/.suibase/suibase-daemon.lock
sh        913015 ----    3r   REG  253,0        0 11666819 /tmp/.suibase/suibase-daemon.lock
suibase-d 913016 ----    3r   REG  253,0        0 11666819 /tmp/.suibase/suibase-daemon.lock
```
If you see "suibase-d"... then it is running.

===

suibase-daemon is the "proxy-server", but as we move forward, the daemon will handle more services (network health monitoring, a lightweight indexer to monitor what was just publish on localnet etc...)

I am hoping that we can get it back up on your setup.

===


**Details about these multiple PID**
This is additional FYI, you do not have to read all of it...

When suibase-daemon crash/panic or a Ctrl-C is received, its parent "sh" process is responsible to restart it (after a few seconds). Furthermore, to make sure there is never two suibase-daemon running at same time, the "sh" has a parent process that does nothing more than holding a file lock (flock).

That is what you see with "lsof" which shows that the same lock is hold for these 3 related processes.

This is a trick that is common, not something I came up with.

Related code: ~/suibase/scripts/common/run-suibase-daemon.sh

**Comment by mario4tier** [comment]
The root cause was not found.

May be this got incidentally "resolved" because of more consistency of the Sui binaries built for all users:
(1) For most setup, the official Mysten Labs Sui binaries are automatically installed.
(2) When Suibase fallback to cargo build, "--locked" is specified.
