### ISSUE TITLE
Invalid private key format error

### ISSUE THREAD

**Issue by georgescharlesbrain** [ChainMovers/suibase#93]
I'm adding my own private keys with 
add_private_keys in the suibase.yaml
It stopped working after I updated today (didn't update for 4 months though).
"Error: Invalid private key format [0x3"
Did you change the support or format of the private keys? Or what do you think is the error?

**Comment by mario4tier** [comment]
You can now do "~/suibase/update" to get the fix.

The problem was a recent change in the JSON output from the Sui keytool command.

The fix to Suibase was:
![image](https://github.com/ChainMovers/suibase/assets/4542410/4004ee01-7682-433a-a510-e53b147621da)


I should have detected that earlier... so I will add today an automated test for the add_private_key.

Thanks for reporting this.

**Comment by mario4tier** [comment]
Take note that "sui client addresses" now show only address with an alias (this is not something I control, I think the Sui binary should display all addresses).

So "add_private_keys" works. The key is added to sui.keystore and can be used, but it needs also an entry in sui.aliases to show up with "sui client addresses".

I think it is a minor problem, but I will try to fix it by tomorrow (I will create dummy "suibase-yaml-x" aliases).

**Comment by georgescharlesbrain** [comment]
It seems "lsui client addresses" does give me an output with auto generated aliases.  
Where should I be able to edit sui.aliases?

**Comment by mario4tier** [comment]
Yes, the auto-generated ones have aliases, so their are shown.

I have to modify the code to do the same with the ones added with "add_private_keys".

In meantime, may be you can edit the alias with "lsui keytool update-alias"?

sui.aliases is co-located with its sui.keystore.

So for localnet:
  ~/suibase/workdirs/localnet/config/sui.aliases



    On Wednesday, February 28, 2024 at 12:56:04 PM EST, Georges-Charles Brain ***@***.***> wrote:  
 
 


It seems "lsui client addresses" does give me an output with auto generated aliases.
Where should I be able to edit sui.aliases?

**Comment by georgescharlesbrain** [comment]
Your advice is much appreciated thanks.

**Comment by mario4tier** [comment]
With latest Suibase, the add_private_keys entries will now have an "alias-<number>" generated.

Example:
![image](https://github.com/ChainMovers/suibase/assets/4542410/aaa6c60c-4f8b-45b4-9ad6-243644abd2e1)
