### ISSUE TITLE
MacOS: Failed to extract binary. Trying to re-download again

### ISSUE THREAD

**Issue by kkomelin** [ChainMovers/suibase#98]
Two users reported the same issue on MacOs after running `localnet start` the first time.
The Github actions for MacOS failed because of the same issue [Failed to extract binary. Trying to re-download again](https://github.com/ChainMovers/suibase/actions/runs/9090884715/job/24984464364#step:9:1939)

**Comment by mario4tier** [comment]
Summary
=======
Mysten Labs did not include many pre-compiled binaries in the latest 1.25 MacOS assets.

Workaround
==========
Users can force Suibase to download/install a specific version with a change to suibase.yaml. Example to force localnet to stay on the last known version working:

```force_tag: "devnet-v1.24.0"```

Details
========
Comparison of 1.24 vs 1.25 released assets.

![Screenshot from 2024-05-15 23-40-53](https://github.com/ChainMovers/suibase/assets/4542410/2d9f0863-0af9-4022-9f4a-7d850b0576ad)

Suibase detects that binaries some required binaries are missing and fails.

I will contact Mysten Labs. This might be a temporary glitch.

**Comment by mario4tier** [comment]
For a list of tags that can be specified in suibase.yaml:
https://github.com/MystenLabs/sui/releases

**Comment by mario4tier** [comment]
Issue now open with Mysten Labs:
   https://github.com/MystenLabs/sui/issues/17770 
   
===

For better user experience in the future, I am considering to implement the following logic:

When the download of the latest succeed but the required binaries are not present, then Suibase will fallback to the previous version (unless being forced in suibase.yaml)

**Comment by kkomelin** [comment]
Thank you @mario4tier!

**Comment by mario4tier** [comment]
Suibase will now always ignore macos arm64 v1.25 release and download previous version instead:

![image](https://github.com/ChainMovers/suibase/assets/4542410/46a48120-e370-434d-a6de-f307271bd839)

A new function "is_assets_valid" in __globals.sh can be used to hard code more exclusion in the future.

===

If somehow you *must* use v1.25 on your setup, then specify "precompiled_bin: false" in suibase.yaml to force a cargo build.

**Comment by kkomelin** [comment]
@mario4tier Thank you for the work but it's a little bit disappointing. Will we exclude more releases in the future? What did Sui guys answered? I can try to reach them out as well if necessary

**Comment by mario4tier** [comment]
Mysten has re-release v1.25 with a fix ( https://github.com/MystenLabs/sui/issues/17770 )

I did revert the workaround in Suibase, so everyone should now be able to update to 1.25

@kkomelin Thanks for reporting this.

**Comment by kkomelin** [comment]
Great @mario4tier. Thank you. 
That's good news because separate conditions for every buggy version of a dependency could lead the code to a mess.
